"""Autogenerated REPORT.md from results.json (spec §15: "autogenererad
REPORT.md med stegverdikt i körordning"). Every number here is read directly
from results.json -- session rule 6 forbids the PDF (built from this same
Markdown, see build_pdf.py) from containing any number absent there.
"""
import json
from pathlib import Path

from . import config

STEP_LABELS = {
    "steg_0a": "Steg 0a -- Datakvalitet (US)",
    "steg_0b": "Steg 0b -- Klocksanity",
    "steg_0c": "Steg 0c -- Orakel-tak (klass-headroom)",
    "steg_1": "Steg 1 -- Basmotorliveness",
    "steg_2": "Steg 2 -- Estimatornull + IC",
    "steg_3": "Steg 3 -- Redundansscreen",
    "steg_4": "Steg 4 -- PC1/effektiv bredd",
    "steg_5": "Steg 5 -- IS-ekonomi + robusthet",
    "steg_6": "Steg 6 -- DSR med ytpool",
    "steg_7": "Steg 7 -- OOS (UCITS, en läsning)",
}

DEATH_REASONS = {
    "steg_0a": "panelen bär inte en volymstrategi (fler än 8 tickers underkända)",
    "steg_0b": "klockan ostationär",
    "steg_0c": "klockdimensionen saknar utrymme",
    "steg_1": "kalender-EWMA-basen död på panelen (eller pipeline trasig)",
    "steg_2": "klockan bär ingen ordningsinformation",
    "steg_3": "volymklockan är redundant (variansklocka eller batteri) / ej lastbärande",
    "steg_4": "klockinkrementet är en gemensam faktor",
    "steg_5": "IS-ekonomi/robusthet otillräcklig",
    "steg_6": "DSR icke-positiv efter ytpoolning",
    "steg_7": "OOS-ytans datamekanism otillräcklig, eller overlay ej >0/40%-tröskeln",
}


def _fmt(v, nd=4):
    if v is None:
        return "n/a"
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, float):
        return f"{v:.{nd}f}"
    return str(v)


def build_report_md(results: dict) -> str:
    lines = []
    lines.append("# TIMGLASET -- autogenererad rapport\n")
    lines.append(f"**config_hash:** `{results['config_hash']}`  ")
    lines.append(f"**seed:** {results['seed']}  ")
    lines.append(f"**strategi:** {results['strategy_name']}  ")
    lines.append(f"**IS-fönster:** {results['data_window']['is_start']} .. "
                  f"{results['data_window']['is_end']}  ")
    lines.append(f"**OOS-fönster (låst, ej läst denna session):** "
                  f"{results['data_window']['oos_start']} .. {results['data_window']['oos_end']}  ")
    lines.append(f"**US-tickerlista sha256:** `{results['us_ticker_list_sha256']}`  ")
    lines.append(f"**OOS-tickerlista sha256 (ej konsumerad):** `{results['oos_ticker_list_sha256']}`  ")
    lines.append(f"**Primärcell:** HL_op={results['primary_cell']['hl_op']}, "
                  f"c={results['primary_cell']['c']}, f={results['primary_cell']['f']}  ")
    lines.append(f"**OOS upplåst denna session:** {results['oos_unlocked_this_session']}  \n")

    stopped_at = results["stopped_at"]
    if stopped_at is None:
        verdict = "SAMTLIGA KÖRDA STEG PASSERADE"
    else:
        reason = DEATH_REASONS.get(stopped_at, "se steg-detalj nedan")
        verdict = f"DÖD -- {stopped_at.upper()}: {reason}"
    lines.append(f"## Verdikt\n\n**{verdict}**\n")

    lines.append("## Stegverdikt (körordning)\n")
    lines.append("| Steg | Kördes | Verdikt |")
    lines.append("|---|---|---|")
    for step_key in results["step_order"]:
        step = results["steps"].get(step_key)
        label = STEP_LABELS.get(step_key, step_key)
        if step is None:
            lines.append(f"| {label} | Nej | -- (avbrutet innan detta steg nåddes) |")
            continue
        passed = step.get("passed")
        verdict_str = "PASS" if passed else ("OKÄNT (gated)" if passed is None else "FAIL")
        lines.append(f"| {label} | Ja | {verdict_str} |")
    lines.append("")

    lines.append("## Nyckeltal per kört steg\n")
    for step_key in results["step_order"]:
        step = results["steps"].get(step_key)
        if step is None:
            continue
        lines.append(f"### {STEP_LABELS.get(step_key, step_key)}\n")
        if step_key == "steg_0a":
            lines.append(f"- Tickers underkända: {step['n_failed']} / {config.STEG0A_MAX_FAILED_TICKERS} tillåtna")
            if step["failed_tickers"]:
                lines.append(f"- Underkända tickers: {', '.join(step['failed_tickers'])}")
        elif step_key == "steg_0b":
            lines.append(f"- Tickers underkända (kräver ALLA godkända): {step['n_failed']} / 40")
            lines.append(f"- Median parvis korr(tau_i, tau_j) (diagnostik): "
                          f"{_fmt(step['median_pairwise_corr_tau_diagnostic'])}")
            worst = sorted(step["per_ticker"].items(),
                            key=lambda kv: kv[1].get("frac_in_range", 0))[:10]
            lines.append("- 10 sämsta tickers (andel dagar med rullande medel-tau i [0.7,1.4]):")
            for t, v in worst:
                lines.append(f"  - {t}: {_fmt(v.get('frac_in_range'))}")
        elif step_key == "steg_0c":
            lines.append(f"- T1-SR: {_fmt(step['t1_sr'])}, Orakel-SR: {_fmt(step['oracle_sr'])}, "
                          f"Increment: {_fmt(step['increment'])} (krav >= {_fmt(step['threshold'], 2)})")
        elif step_key == "steg_1":
            lines.append(f"- T0 reproducerad SR: {_fmt(step['t0_reproduced_sharpe'])} "
                          f"(mål {_fmt(step['t0_target_sharpe'])} +-{_fmt(step['t0_tolerance'], 2)})")
            lines.append(f"- T1 IS-SR (2004-2026): {_fmt(step['t1_is_sharpe'])} "
                          f"(krav >= {_fmt(step['t1_min_required'], 2)})")
        elif step_key == "steg_2":
            lines.append(f"- IC_op: {_fmt(step['ic_op'], 5)} (n={step['ic_op_n_obs']})")
            lines.append(f"- p95(IC_T2): {_fmt(step['ic_t2_p95'], 5)}, medel(IC_T2): "
                          f"{_fmt(step['ic_t2_mean'], 5)}")
            lines.append(f"- Kriterier: |IC|>=0.015: {step['criterion_abs_ic']}, "
                          f"IC_op>p95: {step['criterion_ic_gt_p95']}, "
                          f"gap>=0.005: {step['criterion_ic_gap']}")
            live = step["t2_liveness_assertion"]
            lines.append(f"- T2-liveness (E|z| inom tolerans): {live['passed']} "
                          f"({_fmt(live['frac_within_tolerance'])} av dragningarna)")
        elif step_key == "steg_3":
            lines.append(f"- Direkt-R^2 (Delta-z mot batteri): {_fmt(step['direct_r2'], 5)} "
                          f"(grind vid >= {config.STEG3_R2_KILL})")
            lines.append(f"- Delta-R^2(op|cal,T3): {_fmt(step['delta_r2_op_given_cal_t3'], 5)}, "
                          f"NW-t(op): {_fmt(step['nw_t_op'])}")
        elif step_key == "steg_4":
            lines.append(f"- PC1-andel: {_fmt(step['pc1_share_primary'], 5)} "
                          f"(max {config.STEG4_MAX_PC1_SHARE})")
            lines.append(f"- Dispersion (primär): {_fmt(step['dispersion_primary'], 5)} vs "
                          f"p95-null: {_fmt(step['dispersion_null_p95'], 5)}")
        elif step_key == "steg_5":
            lines.append(f"- IS overlay-SR: {_fmt(step['is_overlay_sharpe'])} "
                          f"(krav >= {config.STEG5_MIN_IS_OVERLAY_SHARPE})")
            lines.append(f"- Bootstrap 90% KI: {[_fmt(x) for x in step['bootstrap_ci_90pct']]}")
            lines.append(f"- Delperiodstecken: {step['subperiod_signs']} "
                          f"({step['n_positive_subperiods']}/3 positiva)")
        elif step_key == "steg_6":
            lines.append(f"- DSR-sannolikhet: {_fmt(step['dsr_prob'], 5)}, z: {_fmt(step['dsr_z'])}, "
                          f"SR0: {_fmt(step['dsr_sr0'])}")
        elif step_key == "steg_7":
            lines.append(f"- Kördes: {step.get('ran')}")
            if step.get("ran"):
                lines.append(f"- Fördatagrind: {step.get('pre_data_gate_passed')}")
        lines.append("")

    lines.append("## Tvilling-liveness (ovillkorliga assertions, spec §7/§1.2.7)\n")
    for name, live in results.get("liveness_assertions", {}).items():
        if "alive" in live:
            lines.append(f"- **{name}**: alive={live['alive']} "
                          f"(coverage_ok={live.get('coverage_ok')}, "
                          f"score_dispersion_ok={live.get('score_dispersion_ok')}, "
                          f"direction_balance_ok={live.get('direction_balance_ok')})")
        else:
            lines.append(f"- **{name}**: {live}")
    lines.append("")

    lines.append("## Levande komponenter (spec §16, oavsett utfall)\n")
    lines.append("1. `opclock.py` -- generellt subordineringsmaskineri (godtycklig aktivitetsproxy kan bli klocka; T3 visar mönstret).")
    lines.append("2. Volymdatakvalitetsrapporten för US-panelen (Steg 0a/0b ovan) -- första systematiska läsningen av kolumnen.")
    lines.append("3. `registry/ytor.jsonl` -- ytregistret (Y1 denna körning).")
    lines.append("4. Klockvals-oraklet (`oracle.py`, rearrangement-taket applicerat på estimatorval, Steg 0c).\n")

    lines.append("## Leveransfiler\n")
    lines.append("- `results.json`, `assertions.jsonl`, `config_frozen.yaml` + `.sha256`, `AVVIKELSER.md` "
                  "(samtliga under `results/timglaset/`).\n")
    return "\n".join(lines)


def main():
    results_path = Path(config.RESULTS_DIR).resolve() / "results.json"
    with open(results_path, encoding="utf-8") as f:
        results = json.load(f)
    report_md = build_report_md(results)
    out_path = Path(__file__).resolve().parent / "REPORT.md"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(report_md)
    print(f"[build_report] Wrote {out_path}")
    return out_path


if __name__ == "__main__":
    main()
